blog_app/urls.py
from django.urls import path , include
from blog_app import views
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from blog_app.sitemap import PostSitemap

sitemaps = {
    'Posts':PostSitemap,
}

app_name = 'blog'
urlpatterns = [
    
    path('', views.home, name='home'),

    path('home/', views.home, name='home'),

    path('blog_detail/<str:slug>/', views.blog_detail, name='blog_detail'),

    path('main_page/', views.main_page, name='main_page'),
    path('search/', views.search, name='search'),

    path('sign_up/', views.sign_up, name='sign_up'),
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),

    path('my_blogs/', views.my_blogs, name='my_blogs'),
    path('write_post/', views.write_post, name='write_post'),
    path('update_post/<int:id>/', views.update_post, name='update_post'),
    path('publish_post/<int:id>/', views.publish_post, name='publish_post'),
    path('delete_post/<int:id>/', views.delete_post, name='delete_post'),

    path('connect_mail/',views.connect_mail, name='connect_mail'),

    path('comment/<int:id>/', views.comment, name='comment'),

    path('reset_password/',
     auth_views.PasswordResetView.as_view(),
     name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(), 
     name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(), 
        name="password_reset_complete"),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
        name='sitemap'),
 
   
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path , include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [ 
    
   path('blog/', include('django.contrib.auth.urls')),
    path('blog/', include('blog_app.urls')),
    path('', include('blog_app.urls')),

    path('tinymce/', include('tinymce.urls')),

    path('admin/', admin.site.urls),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

blog_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User #for creatig user 
from django.utils.text import slugify
from .utils import get_random_hero, get_random_string, get_random_profile_pic


from taggit.managers import TaggableManager


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, null=True)
    slug = models.SlugField(max_length=255,null=True, unique=True, blank=True)
    content = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default=get_random_hero())
    is_published = models.BooleanField(default=False)
    tags = TaggableManager()

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title) + '-' + get_random_string(8)
        super(Post, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('blog:blog_detail', args=[self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post , on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)
    
    def __str__(self):
        return self.body
        
    
        
    

blog_app/forms.py
from django import forms    
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post , Comment
from tinymce.widgets import TinyMCE




class CreateUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['first_name'].widget.attrs.update({'class':'form-control','placeholder':'Firstname'})
        self.fields['last_name'].widget.attrs.update({'class':'form-control','placeholder':'Lastname'})
        self.fields['username'].widget.attrs.update({'class':'form-control','placeholder':'Username'})
        self.fields['email'].widget.attrs.update({'class':'form-control', 'placeholder':'Email'})
        self.fields['password1'].widget.attrs.update({'class':'form-control','placeholder':'Password'})
        self.fields['password2'].widget.attrs.update({'class':'form-control','placeholder':'Confirm Password'})
        
            
    class Meta:
        model = User
        fields = ['first_name','last_name','username', 'email', 'password1', 'password2']


class CreatPostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['tags'].widget.attrs.update({'placeholder':'enter tags'})

    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'tags']
        widgets = {
        'content': TinyMCE(),
        }
    
class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['body']

blog_app/views.py
from django.shortcuts import render, redirect, HttpResponse, HttpResponseRedirect , get_object_or_404
from django.urls import reverse

from .models import Post, Comment
from taggit.models import Tag
from .forms import CreateUserForm , CreatPostForm , CommentForm

from django.contrib.auth.models import Group , User
from django.db.models import Q

from django.contrib.auth.decorators import login_required # django builtin decorator 
from .decorators import  unauthenticated_user

from django.contrib.auth import authenticate, login, logout # authentication functions 
from django.contrib import messages
from .utils import get_random_profile_pic , send_subscriber_mail

from django.core.paginator import Paginator
# Create your views here.

def home(request):
    posts = Post.objects.filter(is_published=True).order_by('-created_at')[:4]
    
    context = {'posts':posts }
    return render(request, 'blog_app/home.html', context)




@unauthenticated_user
def sign_up(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save() #return username 

            group = Group.objects.get(name='user')
            user.groups.add(group)

            messages.success(request, f'Account created for {user}')
            
            login(request, user)
            return redirect('blog:main_page')

        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")
               

    context = {'form':form}
    return render(request, 'blog_app/sign_up.html', context)


@unauthenticated_user
def login_user(request):

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request , username=username , password=password)

        if user is not None:
            login(request, user)
            messages.success(request, f'logged in as {username}')
            return redirect('blog:main_page')
        else:
            messages.info(request, 'Username or Password is invalid !')
            print('message executed')

    context= {}
    return render(request , 'blog_app/login_user.html', context)


@login_required(login_url='blog:login_user')
def logout_user(request):
    logout(request)
    messages.info(request, "Logged Out")
   
    return redirect('blog:home')


def connect_mail(request):
    if request.method == "POST":
        c_email = request.POST.get('c_email')
        send_subscriber_mail(c_email)
    return HttpResponse("You have subscribed")
        

@login_required(login_url='blog:login_user')
def blog_detail(request, slug):
    post = Post.objects.get(slug=slug)

    profile_pic = get_random_profile_pic()
    
    comments = Comment.objects.filter(post = post)
    
    context = {'post':post , 'profile_pic':profile_pic, 'comments':comments}
    return render(request, 'blog_app/detailblog.html', context)


@login_required(login_url='blog:login_user')
def main_page(request):
    posts = Post.objects.filter(is_published=True).order_by('-created_at')
    #show most common tags
    common_tags = Post.tags.most_common()[:5]

    paginator = Paginator(posts, 6) #show 6 objects of posts per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'posts':posts, 'page_obj':page_obj, 'common_tags':common_tags}
    return render(request, 'blog_app/main_page.html', context)


def search(request):
    q = request.GET.get('q')
    posts = None
    if q:
        posts = Post.objects.filter(title__icontains = q)
        print(posts)
    context = {'posts': posts}
    return render(request, 'blog_app/search.html', context)

@login_required(login_url='blog:login_user')
def my_blogs(request):
    posts = Post.objects.filter(author=request.user).order_by('-created_at')
    total_blogs = posts.count()
    active_blogs =posts.filter(is_published=True).count()
    print(total_blogs, active_blogs)

    context = {'posts':posts, 'total_blogs':total_blogs, 'active_blogs':active_blogs}
    return render(request, 'blog_app/my_blogs.html',context)




@login_required(login_url='blog:login_user')
def write_post(request):
    form = CreatPostForm()
    if request.method == "POST":
        form = CreatPostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            form.save_m2m()

            print('blog saved')
            return redirect('blog:main_page')
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")            
    

    context = {'form':form,}
    return render(request, 'blog_app/create_post.html', context)


@login_required(login_url='blog:login_user')
def update_post(request , id):

    current_post = Post.objects.get(id=id)
    form = CreatPostForm(instance=current_post)
    if request.method == 'POST':
        form = CreatPostForm(request.POST, instance=current_post)
        if form.is_valid():
            form.save()
            messages.success(request, "post updated")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")

    context = {'form':form}

    return render(request , 'blog_app/update_post.html', context)


@login_required(login_url='blog:login_user')
def publish_post(request , id):
    Post.objects.filter(id=id).update(is_published=True)
    return HttpResponseRedirect('/blog/my_blogs/')



@login_required(login_url='blog:login_user')
def delete_post(request , id):

    post = Post.objects.get(id=id).delete()
    messages.info(request, f'Post deleted !')

    return HttpResponseRedirect('/blog/my_blogs/')


@login_required(login_url='blog:login_user')
def comment(request, id):
    post = get_object_or_404(Post, id=id)

    # Processing POST requests
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.user = request.user
            new_comment.save()
            return redirect('blog:blog_detail', slug=post.slug)
    else:
        for msg in comment_form.error_messages:
            messages.error(request, f"{msg}: {form.error_messages[msg]}")
    
    return redirect('blog:blog_detail', slug=post.slug)

blog_app/templates/blog_app/create_post.html
{% extends 'blog_app/base.html'%}

{% load static %}

{%block head%}
{{form.media}}
{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col ad-container">
            <span>

            </span>

        </div>
    </div>

    <div class="row">
        <div class="col s12 m12 l3">
            <!-- modal trigger  -->
            <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Formating Instructions</a>

            <!-- Modal Structure -->
            <div id="modal1" class="modal modal-fixed-footer">
                <div class="modal-content">
                    <h4>Formating options for better Representation of your blog </h4>
                    <span>
                        <p style="font-family: Arial; font-size:24px;"> Font style - Arial </p>
                        <p style="font-size: 36px;">Main heading in 36px</p>
                        <p style="font-size: 18px;">some content Lorem ipsum dolor sit amet consectetur adipisicing
                            elit.
                            Unde voluptatum veritatis accusantium nam illo excepturi quibusdam asperiores quos? Illum
                            quidem
                            maiores soluta placeat!</p>
                        <p style="font-size: 24px;">Sub heading in 24px</p>
                        <p style="font-size: 18px;"> content in 18px </p>
                        <p style="font-size: 18px;"> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti
                            quis
                            magni, fugiat iusto laudantium nemo, minima inventore id pariatur, nesciunt nobis
                            dignissimos
                            fugit. Ex inventore velit sed perspiciatis tempora minima consequuntur. Eveniet, placeat!
                        </p>
                    </span>
                </div>
                <div class="modal-footer">
                    <a class="modal-close waves-effect waves-green btn-flat">ok</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col s12 m12 l9">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="input-field">
                    {{form.title}}
                    <label for="id_title">Title</label>
                </div>

                <div class="input-field">
                    {{form.content}}
                </div>

                <div class="input-field">
                    {{form.tags}}
                </div>
                <sup>Enter comma saperated values </sup>

                <Button class="waves-effect orange waves-light btn-small right" type="submit"><i
                        class="material-icons right">save</i>Save</Button>

            </form>
        </div>
    </div>

</div>
</div>




{% endblock %}

blog_app/templates/blog_app/detailblog.html
{% extends 'blog_app/base.html'%}


{% load static %}
{% block head%}


{% endblock %}


{% block content%}
<div class="container">
    <div class="row">
        <div class="col">
            <span>ad container </span>
        </div>
    </div>

    <div class="row">
        <div class="col s12 offset-m1 m10 offset-l3 l5">
            <div class="card">
                <div class="card-image">
                    <img src="{{post.image.url}}" alt="">
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col s12 m8 offset-m2 l7 offset-l2">
            <div class="card-panel grey lighten-5 z-depth-1">
                <div class="row valign-wrapper">
                    <div class="col s2">
                        <img src="{{MEDIA_URL}}{{profile_pic}}" alt="" class="circle responsive-img">
                    </div>
                    <div class="col s10">
                        <span class="black-text">
                            <h4>{{post.title | capfirst }}</h4>
                            <h6>{{post.author|capfirst}}</h6>
                            <p>{{post.created_at | date}}</p>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="section white">
            <div class="col s12 offset-m1 m10 offset-l1 l9">
                <hr>
                <p class="flow-text">{{post.content|safe}}</p>
            </div>
        </div>
    </div>


    <div class="row">

        <div class="col s12  m10 offset-l1 l6">
            <form action="{% url 'blog:comment' post.id %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="body">
                        <strong>
                            I would also like to make a statement:
                        </strong>
                    </label>
                    <textarea type="text" class="form-control" id="comment-body" name="body"
                        style="resize:none; height:10em;" required></textarea>
                </div>
                <! - Submit button ->
                    <button type="submit" class="btn btn-primary">send </button>
            </form>
        </div>

        <div class="col s12  m10 offset-l1 l6">
            <h5> There are {{comments.count}} comments </h5>
            {% for comment in comments %}
            <div class="card comment-card">
                <div class="card-content">

                    <strong style="color: gray">
                        {{ comment.user }}
                    </strong>
                    <span style="color: green">
                        {{ comment.created_at|date:"d-m-Y" }}
                    </span>:
                    <br>

                    <span style="font-family: inherit; font-size: 1em;">
                        {{ comment.body }}</span>

                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>


</div>






<script src="{% static 'tinymce/js/prism.js' %}"></script>
{% endblock%}

blog_app/templates/blog_app/footer.html
<footer class="page-footer blue-grey darken-3">
    <div class="container">
        <div class="row">
            <div class="col l4 s12">
                <h5 class="white-text">ABOUT </h5>
                <p class="grey-text text-lighten-4"> Hi , I am Yash. The developer of dev-blogs. This blog site is made
                    for developers around the world and the web is completely made in Django.

                </p>
            </div>
            <div class="col l4 s12">
                <h5 class="white-text">CONTACT US</h5>

                <p class="grey-text text-lighten-4"><i class="material-icons left">mail</i><a
                        href="mailto:yashranka187@gmail.com">yashranka187@gmail.com</a></p>
            </div>
            <div class="col l4  s12">
                <h5 class="white-text">Stay Connected !</h5>
                <form action="{% url 'blog:connect_mail' %}" method='post'>
                    {% csrf_token %}
                    <input class="form-control white-text" type="email" name="c_email" id="" placeholder=" Email">
                    <button class="btn btn-small white black-text" type="submit">connect</button>
                </form>


            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2020 dev-blogs

        </div>
    </div>
</footer>

blog_app/templates/blog_app/login_user.html
{% extends 'blog_app/base.html'%}
{% load static %}

{% block head%}
<style>
    .row {
        justify-content: center;
        align-items: center;
    }


    .form-col {
        margin-top: 100px;

    }

    .hero-image {
        margin-top: 100px;
        width: 100%;
        height: auto;
    }
</style>
{% endblock %}


{% block content%}
<div class="container">
    <div class="row">
        <div class="col s12  offset-m2 m8 l4 form-col">
            <form action="" method="POST">
                {% csrf_token %}

                <h4 class="center-align">Login</h4>


                <input type="text" name="username" maxlength="255" class="form-control" placeholder="Username"
                    required="true">



                <!-- password -->
                <input type="password" name="password" maxlength="255" class="form-control" placeholder="Password"
                    required="true">



                <button class="waves-effect waves-light btn-small" type="submit">Login</button>
                <!-- Social register -->
                <!-- <p class="center-align">or sign up with:</p>
                <div class="row">
                    <div class="col offset-s4 s12 offset-m4 m12 offset-l4 l12 ">
                        <a href="#" class="" role="button"><i class="fab fa-facebook-f light-blue-text"></i></a>

                        <a href="#" class="" role="button"><i class="fab fa-twitter light-blue-text"></i></a>

                        <a href="#" class="" role="button"><i class="fab fa-linkedin-in light-blue-text"></i></a>

                        <a href="#" class="" role="button"><i class="fab fa-github light-blue-text"></i></a>
                    </div>
                </div>
                <hr> -->
                <p class="right">Forgot Password ? <a href="{% url 'blog:reset_password' %}">click here to reset</a>
                </p>
                <p class="right">Don't have an account? <a href="{% url 'blog:sign_up' %}">register here</a>
                </p>

            </form>
        </div>

        <div class="col s12 m12 l6">
            <img class="hero-image" src="{% static 'images/login.jpg'%}" alt="hro image">

        </div>


    </div>


</div>
{% endblock %}

blog_app/templates/blog_app/main_page.html
{% extends 'blog_app/base.html'%}
{% load static %}

{% block head %}
<style>
    .card-content {
        height: 175px;
    }
</style>
{% endblock%}
{% block content%}

<div class="container">
    <div class="row">
        <div class="col ad-container">
            <span>

            </span>
        </div>
    </div>

    <div class="row">
        <div class="nav-wrapper">
            <form action="{% url 'blog:search' %}" method="GET">
                <div class="input-field">
                    <input id="search" name="q" type="search" placeholder="search ...." required>
                    <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                    <i class="material-icons">close</i>
                </div>
            </form>
        </div>
    </div>

    <div class="row">

        <p>common tags:</p>
        {% for tag in common_tags%}
        <span class="badge indigo lighten-2 left white-text">
            #{{tag}}
        </span>
        {%endfor%}

    </div>
    <div class="row">

        {% for post in page_obj%}

        <div class="col s12 m6 l4   ">

            <div class="card  hoverable">
                <div class="card-image">
                    <img src="{{post.image.url}}" alt="">
                </div>

                <div class="card-content">
                    <a href="{% url 'blog:blog_detail' post.slug %}">
                        <span class="card-title">
                            <h4 class="header" class="blue-text">{{post.title}}</h4>
                        </span>
                    </a>
                    {% for tag in post.tags.all %}
                    <span class="badge green left white-text">
                        #{{tag}}
                    </span>
                    {% endfor %}
                </div>

                <div class="card-action">
                    <div class="span badge">{{post.author}}</div>
                </div>

            </div>

        </div>
        {% endfor %}
    </div>

    <div class="row center-align">
        <ul class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left fa-lg"
                        aria-hidden="true"></i></a>
                {% if page_obj.previous_page_number > 1%} <a href="?page=1">first ..... </a> {% endif %}

                <a href="?page={{ page_obj.previous_page_number}}">{{page_obj.previous_page_number}}</a>
                {% endif %}

                <li class="active"><a href="">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
                </li>



                {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}">{{page_obj.next_page_number}}</a>
                {% if page_obj.next_page_number != page_obj.paginator.num_pages %} <a
                    href="?page={{ page_obj.paginator.num_pages }}"> ..... last</a> {% endif %}
                <a href="?page={{ page_obj.next_page_number}}"><i class="fa fa-angle-right fa-lg"
                        aria-hidden="true"></i></a>
                {% endif %}
            </span>
        </ul>

    </div>

</div>



{% endblock%}

blog_app/templates/blog_app/my_blogs.html
{% extends 'blog_app/base.html'%}
{% load static %}

{% block content%}
<div class="container">
    <div class="row">
        <div class="col">
            <h2 class="header">My Blogs</h2>
        </div>
    </div>

    <div class="row">
        <div class="col s12 m8 l6">


            <ul class="collapsible">

                {% for post in posts %}


                <li>
                    {% if post.is_published%}
                    <div class="collapsible-header green lighten-3"> {% else %} <div
                            class="collapsible-header  lighten-3"> {% endif %}
                            {{post.title | capfirst}}
                        </div>
                        <div class="collapsible-body">

                            {% if not post.is_published %}
                            <a href="{% url 'blog:publish_post' post.id %}"
                                class="waves-effect waves-light green btn-small"><i
                                    class="material-icons left">publish</i>publish</a>

                            {% else %}
                            <a class="waves-effect waves-light btn green btn-small disabled"><i
                                    class="material-icons left">publish</i>publish</a>
                            {% endif %}

                            <a href="{% url 'blog:update_post' post.id %}"
                                class="waves-effect waves-light orange btn-small"><i
                                    class="material-icons left">update</i>update</a>
                            <br><br>

                            <a href="#delete{{post.id}}" class="waves-effect waves-light red btn-small modal-trigger"><i
                                    class="material-icons right">delete</i>delete</a>

                            <a class="waves-effect waves-light btn btn-small modal-trigger" href="#{{post.id}}"><i
                                    class="material-icons right">crop_free</i>Preview</a>


                        </div>
                </li>

                <div id="delete{{post.id}}" class="modal">
                    <div class="modal-content">
                        <p class="flow-text">Do yout really want to delete {{post.title}} ?</p>
                    </div>
                    <div class="modal-footer">
                        <a class="modal-close waves-effect waves-green btn-flat">No take me back</a>
                        <a href="{% url 'blog:delete_post' post.id %}"
                            class="modal-close waves-effect  waves-green btn-flat">Yes delete it</a>
                    </div>
                </div>

                <div id="{{post.id}}" class="modal">
                    <div class="modal-content">
                        <h2>{{post.title | capfirst}}</h2>
                        <hr>
                        <p>{{post.content | safe }}</p>
                    </div>
                    <div class="modal-footer">
                        <a href="#!" class="modal-close waves-effect waves-green btn-flat">Agree</a>
                    </div>
                </div>

                {% endfor %}
            </ul>



        </div>
        <div class="col m4 l3 hide-on-small-only">
            <ul class="collection">
                <li class="collection-item">Total blogs <span class="badge">{{total_blogs}}</span>
                </li>
                <li class="collection-item">Published <span class="badge green lighten-3">{{active_blogs}}</span></li>

            </ul>
        </div>
    </div>


</div>

{% endblock %}

blog_app/templates/blog_app/navbar.html
{%load static%}
<nav class="blue-grey darken-4">
    <div class="nav-wrapper">
        <a href="{% url 'blog:home' %}" class="brand-logo hide-on-small-only"><i class="material-icons">layers
            </i>Dev-Blogs</a>
        <a href="#!" class="brand-logo small hide-on-med-and-up">Dev-Blogs</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">

            {% if user.is_authenticated%}

            <li><a href="{% url 'blog:home' %}">Home</a></li>
            <li><a href="{% url 'blog:write_post' %}">Write</a></li>
            <li><a class="chip red white-text"><strong>{{request.user}}</strong></a></li>
            <li><a class="dropdown-trigger" href="#!" data-target="dropdown1"><i class="material-icons">person</i></a>
            </li>

            {% else %}

            <li><a href="{% url 'blog:sign_up' %}">Sign Up</a></li>
            <li><a href="{% url 'blog:login_user' %}">Login</a></li>
            {% endif %}

        </ul>
    </div>
</nav>

<ul class="sidenav" id="mobile-demo">

    <li class="center-align">
        <h3 class="flow-text">Dev-Blogs</h3>
    </li>
    <li class="divider"></li>
    {% if user.is_authenticated%}
    <li>
        <div class="user-view">
            <div class="background">
                <img src="{% static 'images/profile_bg.jpg' %}">
            </div>
            <p><img class="circle" src="{% static 'images/p1.jpg' %}"></p>
            <span class="black-text name">{{request.user}}</span>
            <span class="black-text email">{{request.user.email}}</span>
        </div>
    </li>
    <li><a href="{% url 'blog:home' %}"><i class="material-icons">home</i>Home</a></li>
    <li><a href="{% url 'blog:my_blogs'%}"><i class="material-icons">web</i>My blogs</a></li>
    <li><a href="{% url 'blog:write_post' %}"><i class="material-icons">edit</i>Write</a></li>
    <li class="divider"></li>
    <li><a href="{% url 'blog:logout_user' %}"><i class="material-icons">power_settings_new</i>Logout</a></li>
    {% else %}
    <li><a href="{% url 'blog:home' %}">Home</a></li>
    <li><a href="{% url 'blog:login_user' %}">Login</a></li>
    <li><a href="{% url 'blog:sign_up' %}">Sign Up</a></li>


    {% endif %}



</ul>

<ul id="dropdown1" class="dropdown-content">
    <li><a href="{% url 'blog:my_blogs'%}"><i class="material-icons">web</i>My blogs</a></li>
    <li class="divider"></li>
    <li><a href="{% url 'blog:logout_user' %}"><i class="material-icons">power_settings_new</i>Logout</a></li>

</ul>